### PR TITLE
Release/1.13

### LINKED ISSUE #7: Missing CONTRIBUTING.md
Failed cookbook quality contributing file metric on public Supermarket

> Failure: To pass this metric, your cookbook metadata must include a source url, the source url must be in the form of https://github.com/user/repo, and your repo must contain a CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by jazaval**
Fixes an issue with ChefSpec when wrapping the `keep_awake` recipe.
Fixes an idempotence issue with the `keychain` resource.
Adds a CONTRIBUTING.md! (resolved #7)

### CODE REVIEW

File: libraries/system.rb [hunk 1]
```diff
@@ -3,12 +3,8 @@ module System
     class FormFactor
       attr_reader :machine_model
 
-      def initialize(machine_model = nil)
-        @machine_model = if Chef.node.nil?
```
Comment (hushlorentz) [inline libraries/system.rb]: I know these were all deleted, but you could use a ternary for a one-line if/else:

@machine_model = Chef.node.nil? ? machine_model : Chef.node['hardware']['machine_model']

Comment (mjmerin) [reply libraries/system.rb]: Indeed!
